model_list:
  - model_name: local-vllm
    litellm_params:
      model: os.environ/VLLM_LITELLM_MODEL
      api_base: os.environ/VLLM_API_BASE
      api_key: os.environ/VLLM_API_KEY

litellm_settings:
  callbacks:
    - prometheus
  success_callback:
    - mlflow
  require_auth_for_metrics_endpoint: false

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
