services:
  vllm:
    container_name: vllm
    image: vllm/vllm-openai:${VLLM_IMAGE_TAG:-v0.22.0-cu129-ubuntu2404}
    command: >
      --model ${VLLM_MODEL_PATH}
      --served-model-name ${VLLM_SERVED_MODEL_NAME}
      --max-model-len ${VLLM_MAX_MODEL_LEN}
      --max-num-batched-tokens ${VLLM_MAX_NUM_BATCHED_TOKENS}
      --gpu-memory-utilization ${VLLM_GPU_MEMORY_UTILIZATION}
      --generation-config /app
      --limit-mm-per-prompt '{"image": 4, "video": 0}'
      --tensor-parallel-size ${VLLM_TENSOR_PARALLEL_SIZE}
      --port ${CONTAINER_PORT:-8000}
      ${VLLM_EXTRA_ARGS:-}
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - HF_TOKEN=${HF_TOKEN:-}
      - NCCL_DEBUG=${NCCL_DEBUG:-INFO}
      - PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}
      - VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=${VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS:-1}
    ports:
      - "${HOST_PORT:-18000}:${CONTAINER_PORT:-8000}"
    volumes:
      - ${MODEL_LOCAL_PATH:-../../models}:/models
      - ./generation_config.json:/app/generation_config.json
      # - ./models:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT:-8000}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              # count: all
              capabilities: [gpu]
    networks:
      - llm-net

networks:
  llm-net:
    external: true
